# Change these first
owner: craftbuy # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: CraftBuy.ru Site
    url: $CRAFTBUY_SITE
    icon: https://craftbuy.ru/favicon.ico
    maxResponseTime: 30000 # default: 30000
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 403
  #- name: CraftBuy.ru Service 2
    #check: "tcp-ping"
    #url: $CRAFTBUY_SERVICE2
    #port: $CRAFTBUY_SERVICE_PORT
    #icon: https://craftbuy.ru/favicon.ico
    #maxResponseTime: 5000 # default: 30000
  - name: CraftBuy.ru Service 3
    check: "tcp-ping"
    url: $CRAFTBUY_SERVICE3
    port: $CRAFTBUY_SERVICE_PORT
    icon: https://craftbuy.ru/favicon.ico
    maxResponseTime: 5000 # default: 30000
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://craftbuy.ru/assets/img/logo_black.png
  name: Uptime
  theme: light
  introTitle: ""
  introMessage: Uptime monitor and status page, powered entirely by GitHub.
  navbar:
    - title: Back to site
      href: https://craftbuy.ru
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
